# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'schenky_update2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Schenky(object):
    def setupUi(self, Schenky):
        Schenky.setObjectName("Schenky")
        Schenky.resize(1088, 614)
        self.centralwidget = QtWidgets.QWidget(Schenky)
        self.centralwidget.setObjectName("centralwidget")
        self.keyLabel = QtWidgets.QLabel(self.centralwidget)
        self.keyLabel.setGeometry(QtCore.QRect(40, 10, 59, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.keyLabel.setFont(font)
        self.keyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.keyLabel.setObjectName("keyLabel")
        self.keyCombo = QtWidgets.QComboBox(self.centralwidget)
        self.keyCombo.setGeometry(QtCore.QRect(110, 20, 191, 31))
        self.keyCombo.setObjectName("keyCombo")
        self.keyCombo.addItem("")
        self.keyCombo.addItem("")
        self.keyCombo.addItem("")
        self.keyCombo.addItem("")
        self.keyCombo.addItem("")
        self.keyCombo.addItem("")
        self.keyCombo.addItem("")
        self.keyCombo.addItem("")
        self.keyCombo.addItem("")
        self.keyCombo.addItem("")
        self.keyCombo.addItem("")
        self.keyCombo.addItem("")
        self.keyCombo.addItem("")
        self.keyCombo.addItem("")
        self.keyCombo.addItem("")
        self.previewScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.previewScrollArea.setGeometry(QtCore.QRect(30, 270, 991, 281))
        self.previewScrollArea.setWidgetResizable(True)
        self.previewScrollArea.setObjectName("previewScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 989, 279))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.imageLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.imageLabel.setGeometry(QtCore.QRect(0, 0, 991, 281))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.previewScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.previewLabel = QtWidgets.QLabel(self.centralwidget)
        self.previewLabel.setGeometry(QtCore.QRect(30, 240, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.previewLabel.setFont(font)
        self.previewLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.previewLabel.setObjectName("previewLabel")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(938, 240, 113, 25))
        self.refreshButton.setObjectName("refreshButton")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(590, 240, 341, 23))
        self.checkBox.setObjectName("checkBox")
        self.zoomInButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomInButton.setGeometry(QtCore.QRect(1026, 270, 25, 25))
        self.zoomInButton.setObjectName("zoomInButton")
        self.zoomOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomOutButton.setGeometry(QtCore.QRect(1026, 300, 25, 25))
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(110, 70, 911, 141))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        
        self.widget = QtWidgets.QWidget()
        self.widget.setGeometry(QtCore.QRect(0, 0, 931, 141))
        self.widget.setStyleSheet("QWidget { background: white }")
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1050, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 911, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addWidget(self.widget_3)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.widget_2 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.widget_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1012, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton.setMinimumSize(QtCore.QSize(1000, 0))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.widget_2)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.widget_4 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.widget_4)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 911, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addWidget(self.widget_4)
        
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 70, 71, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)

        self.scrollArea.setWidget(self.widget)
        self.widget.updateGeometry()        

        Schenky.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Schenky)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        Schenky.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Schenky)
        self.statusbar.setObjectName("statusbar")
        Schenky.setStatusBar(self.statusbar)
        self.dockWidget_3 = QtWidgets.QDockWidget(Schenky)
        self.dockWidget_3.setMaximumSize(QtCore.QSize(402, 524287))
        self.dockWidget_3.setStyleSheet("")
        self.dockWidget_3.setFloating(False)
        self.dockWidget_3.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable|QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.dockWidget_3.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.dockWidgetContents_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 381, 571))
        self.tabWidget_2.setMinimumSize(QtCore.QSize(100, 0))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.propertiesTable_3 = QtWidgets.QTableWidget(self.tab_4)
        self.propertiesTable_3.setGeometry(QtCore.QRect(0, 0, 381, 541))
        self.propertiesTable_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.propertiesTable_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.propertiesTable_3.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.propertiesTable_3.setAlternatingRowColors(True)
        self.propertiesTable_3.setTextElideMode(QtCore.Qt.ElideRight)
        self.propertiesTable_3.setWordWrap(True)
        self.propertiesTable_3.setCornerButtonEnabled(True)
        self.propertiesTable_3.setRowCount(7)
        self.propertiesTable_3.setColumnCount(2)
        self.propertiesTable_3.setObjectName("propertiesTable_3")
        item = QtWidgets.QTableWidgetItem()
        self.propertiesTable_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.propertiesTable_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.propertiesTable_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable)
        self.propertiesTable_3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.propertiesTable_3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.propertiesTable_3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.propertiesTable_3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.propertiesTable_3.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.propertiesTable_3.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.propertiesTable_3.setItem(6, 0, item)
        self.propertiesTable_3.horizontalHeader().setDefaultSectionSize(125)
        self.propertiesTable_3.horizontalHeader().setStretchLastSection(True)
        self.propertiesTable_3.verticalHeader().setVisible(False)
        self.propertiesTable_3.verticalHeader().setDefaultSectionSize(25)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.dockWidget_3.setWidget(self.dockWidgetContents_2)
        Schenky.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_3)
        self.actionNew = QtWidgets.QAction(Schenky)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(Schenky)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(Schenky)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(Schenky)
        self.actionExit.setObjectName("actionExit")
        self.actionCopy = QtWidgets.QAction(Schenky)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(Schenky)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(Schenky)
        self.actionPaste.setObjectName("actionPaste")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(Schenky)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Schenky)

    def retranslateUi(self, Schenky):
        _translate = QtCore.QCoreApplication.translate
        Schenky.setWindowTitle(_translate("Schenky", "Schenky"))
        self.keyLabel.setText(_translate("Schenky", "Key:"))
        self.keyCombo.setStatusTip(_translate("Schenky", "Choose a key"))
        self.keyCombo.setItemText(0, _translate("Schenky", "C major/A minor"))
        self.keyCombo.setItemText(1, _translate("Schenky", "C# major/A# minor"))
        self.keyCombo.setItemText(2, _translate("Schenky", "Db major/Bb minor"))
        self.keyCombo.setItemText(3, _translate("Schenky", "D major/B minor"))
        self.keyCombo.setItemText(4, _translate("Schenky", "Eb major/C minor"))
        self.keyCombo.setItemText(5, _translate("Schenky", "E major/C# minor"))
        self.keyCombo.setItemText(6, _translate("Schenky", "F major/D minor"))
        self.keyCombo.setItemText(7, _translate("Schenky", "F# major/D# minor"))
        self.keyCombo.setItemText(8, _translate("Schenky", "Gb major/Eb minor"))
        self.keyCombo.setItemText(9, _translate("Schenky", "G major/E minor"))
        self.keyCombo.setItemText(10, _translate("Schenky", "Ab major/F minor"))
        self.keyCombo.setItemText(11, _translate("Schenky", "A major/F# minor"))
        self.keyCombo.setItemText(12, _translate("Schenky", "Bb major/G minor"))
        self.keyCombo.setItemText(13, _translate("Schenky", "B major/G# minor"))
        self.keyCombo.setItemText(14, _translate("Schenky", "Cb major/Ab minor"))
        self.previewScrollArea.setStatusTip(_translate("Schenky", "Schenkerian graph preview"))
        self.previewLabel.setText(_translate("Schenky", "Preview:"))
        self.refreshButton.setStatusTip(_translate("Schenky", "Refresh Schenkerian graph"))
        self.refreshButton.setText(_translate("Schenky", "Refresh"))
        self.checkBox.setText(_translate("Schenky", "Auto-refresh (uncheck for better performance)"))
        self.zoomInButton.setStatusTip(_translate("Schenky", "Zoom In"))
        self.zoomInButton.setText(_translate("Schenky", "+"))
        self.zoomOutButton.setStatusTip(_translate("Schenky", "Zoom Out"))
        self.zoomOutButton.setText(_translate("Schenky", "-"))
        self.widget.setStatusTip(_translate("Schenky", "Add/remove note"))
        self.pushButton.setText(_translate("Schenky", "PushButton"))
        self.label.setText(_translate("Schenky", "Measure:"))
        self.label_3.setText(_translate("Schenky", "Treble:"))
        self.label_2.setText(_translate("Schenky", "Bass:"))
        self.menuFile.setTitle(_translate("Schenky", "File"))
        self.menuEdit.setTitle(_translate("Schenky", "Edit"))
        self.dockWidget_3.setStatusTip(_translate("Schenky", "Properties panel"))
        self.dockWidget_3.setWindowTitle(_translate("Schenky", "Properties"))
        self.propertiesTable_3.setStatusTip(_translate("Schenky", "Edit note properties"))
        item = self.propertiesTable_3.horizontalHeaderItem(0)
        item.setText(_translate("Schenky", "Property"))
        item = self.propertiesTable_3.horizontalHeaderItem(1)
        item.setText(_translate("Schenky", "Value"))
        __sortingEnabled = self.propertiesTable_3.isSortingEnabled()
        self.propertiesTable_3.setSortingEnabled(False)
        item = self.propertiesTable_3.item(0, 0)
        item.setText(_translate("Schenky", "ID"))
        item = self.propertiesTable_3.item(1, 0)
        item.setText(_translate("Schenky", "Note"))
        item = self.propertiesTable_3.item(2, 0)
        item.setText(_translate("Schenky", "Accidental"))
        item = self.propertiesTable_3.item(3, 0)
        item.setText(_translate("Schenky", "Register"))
        item = self.propertiesTable_3.item(4, 0)
        item.setText(_translate("Schenky", "Slurs to..."))
        item = self.propertiesTable_3.item(5, 0)
        item.setText(_translate("Schenky", "Unfolds with..."))
        item = self.propertiesTable_3.item(6, 0)
        item.setText(_translate("Schenky", "Part of lines..."))
        self.propertiesTable_3.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Schenky", "Note"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Schenky", "Slurs"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("Schenky", "Unfoldings"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Schenky", "Lines"))
        self.actionNew.setText(_translate("Schenky", "New"))
        self.actionNew.setStatusTip(_translate("Schenky", "Create a new file"))
        self.actionNew.setShortcut(_translate("Schenky", "Ctrl+N"))
        self.actionOpen.setText(_translate("Schenky", "Open"))
        self.actionOpen.setStatusTip(_translate("Schenky", "Open a file"))
        self.actionOpen.setShortcut(_translate("Schenky", "Ctrl+O"))
        self.actionSave.setText(_translate("Schenky", "Save"))
        self.actionSave.setStatusTip(_translate("Schenky", "Save file"))
        self.actionExit.setText(_translate("Schenky", "Exit"))
        self.actionCopy.setText(_translate("Schenky", "Copy"))
        self.actionCopy.setShortcut(_translate("Schenky", "Ctrl+C"))
        self.actionCut.setText(_translate("Schenky", "Cut"))
        self.actionCut.setShortcut(_translate("Schenky", "Ctrl+X"))
        self.actionPaste.setText(_translate("Schenky", "Paste"))
        self.actionPaste.setShortcut(_translate("Schenky", "Ctrl+V"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Schenky = QtWidgets.QMainWindow()
    ui = Ui_Schenky()
    ui.setupUi(Schenky)
    Schenky.show()
    sys.exit(app.exec_())
